name: Go Build and Test

on:
  push:
  pull_request:

jobs:
  build_and_test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install frontend dependencies
        run: go mod tidy
        working-directory: ./frontend
      - name: Run tests
        run: go test -v ./...
        working-directory: ./frontend
      - name: Build frontend
        run: go build -o frontend_binary
        working-directory: ./frontend
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-artifact
          path: ./frontend/frontend_binary

  build_frontend_docker_image:
    runs-on: ubuntu-latest
    needs: [ build_and_test_frontend ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-artifact
          path: ./frontend
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set environment variables
        run: |
          echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV
      - name: Build and push Docker image
        run: chmod +x ci/build-push-frontend-docker-image.sh && ci/build-push-frontend-docker-image.sh


  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install backend dependencies
        run: go mod tidy
        working-directory: ./backend
      - name: Build backend
        run: go build -o backend_binary
        working-directory: ./backend
      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: ./backend/backend_binary

  build_backend_docker_image:
    runs-on: ubuntu-latest
    needs: [ build_backend ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-artifact
          path: ./backend
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set environment variables
        run: |
          echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV
      - name: Build and push Docker image
        run: chmod +x ci/build-push-backend-docker-image.sh && ci/build-push-backend-docker-image.sh